import type {
  AppData,
  CatalogueItem,
  CollectionEvent,
  CollectionItem,
  PriceConfidence,
  SetProgress,
  StorageLocation,
  WishlistItem,
} from "./types";

function samplePriceHistory(
  source: string,
  confidence: PriceConfidence,
  entries: Array<[string, number, string?]>,
) {
  return entries.map(([observedAt, valueMinor, variantLabel]) => ({
    observedAt: `${observedAt}T00:00:00.000Z`,
    valueMinor,
    confidence,
    source,
    variantLabel,
  }));
}

export const catalogue: CatalogueItem[] = [
  {
    id: "card-charizard-151",
    type: "card",
    name: "Charizard ex",
    set: "Scarlet & Violet 151",
    number: "199/165",
    rarity: "Special Illustration Rare",
    image: "https://images.pokemontcg.io/sv3pt5/199_hires.png",
    hasPrice: true,
    valueMinor: 11800,
    confidence: "Fair",
    priceSource: "pokemon-tcg-api-cardmarket",
    priceObservedAt: "2026-06-01T00:00:00.000Z",
    priceHistory: samplePriceHistory("pokemon-tcg-api-cardmarket", "Fair", [
      ["2026-04-01", 10800, "Holofoil"],
      ["2026-05-01", 11400, "Holofoil"],
      ["2026-06-01", 11800, "Holofoil"],
    ]),
    variantOptions: [
      { label: "Holofoil", valueMinor: 11800, confidence: "Fair", source: "pokemon-tcg-api-cardmarket", observedAt: "2026-06-01T00:00:00.000Z" },
      { label: "Reverse Holofoil" },
    ],
  },
  {
    id: "card-umbreon-vmax",
    type: "card",
    name: "Umbreon VMAX",
    set: "Evolving Skies",
    number: "215/203",
    rarity: "Secret Rare",
    image: "https://images.pokemontcg.io/swsh7/215_hires.png",
    hasPrice: true,
    valueMinor: 74000,
    confidence: "Strong",
    priceSource: "pokemon-tcg-api",
    priceObservedAt: "2026-06-01T00:00:00.000Z",
    priceHistory: samplePriceHistory("pokemon-tcg-api", "Strong", [
      ["2026-04-01", 68000, "Holofoil"],
      ["2026-05-01", 71500, "Holofoil"],
      ["2026-06-01", 74000, "Holofoil"],
    ]),
    variantOptions: [
      { label: "Holofoil", valueMinor: 74000, confidence: "Strong", source: "pokemon-tcg-api", observedAt: "2026-06-01T00:00:00.000Z" },
    ],
  },
  {
    id: "card-mew-ex",
    type: "card",
    name: "Mew ex",
    set: "Scarlet & Violet 151",
    number: "193/165",
    rarity: "Special Illustration Rare",
    image: "https://images.pokemontcg.io/sv3pt5/193_hires.png",
    hasPrice: true,
    valueMinor: 3500,
    confidence: "Fair",
    priceSource: "pokemon-tcg-api-cardmarket",
    priceObservedAt: "2026-06-01T00:00:00.000Z",
    priceHistory: samplePriceHistory("pokemon-tcg-api-cardmarket", "Fair", [
      ["2026-04-01", 3100, "Holofoil"],
      ["2026-05-01", 3300, "Holofoil"],
      ["2026-06-01", 3500, "Holofoil"],
    ]),
    variantOptions: [
      { label: "Holofoil", valueMinor: 3500, confidence: "Fair", source: "pokemon-tcg-api-cardmarket", observedAt: "2026-06-01T00:00:00.000Z" },
      { label: "Normal" },
    ],
  },
  {
    id: "card-pikachu",
    type: "card",
    name: "Pikachu",
    set: "Crown Zenith",
    number: "160/159",
    rarity: "Secret Rare",
    image: "https://images.pokemontcg.io/swsh12pt5/160_hires.png",
    hasPrice: true,
    valueMinor: 1450,
    confidence: "Strong",
    priceSource: "pokemon-tcg-api",
    priceObservedAt: "2026-06-01T00:00:00.000Z",
    priceHistory: samplePriceHistory("pokemon-tcg-api", "Strong", [
      ["2026-04-01", 1320, "Normal"],
      ["2026-05-01", 1410, "Normal"],
      ["2026-06-01", 1450, "Normal"],
    ]),
    variantOptions: [
      { label: "Normal", valueMinor: 1450, confidence: "Strong", source: "pokemon-tcg-api", observedAt: "2026-06-01T00:00:00.000Z" },
      { label: "Reverse Holofoil" },
    ],
  },
  {
    id: "sealed-151-bundle",
    type: "sealed",
    name: "151 Booster Bundle",
    set: "Scarlet & Violet 151",
    number: "Sealed",
    rarity: "Booster bundle",
    hasPrice: true,
    valueMinor: 3200,
    confidence: "Weak",
    priceSource: "tcgcsv",
    priceObservedAt: "2026-06-01T00:00:00.000Z",
    priceHistory: samplePriceHistory("tcgcsv", "Weak", [
      ["2026-04-01", 2800, "Factory sealed"],
      ["2026-05-01", 3000, "Factory sealed"],
      ["2026-06-01", 3200, "Factory sealed"],
    ]),
    variantOptions: [
      { label: "Factory sealed", valueMinor: 3200, confidence: "Weak", source: "tcgcsv", observedAt: "2026-06-01T00:00:00.000Z" },
    ],
  },
  {
    id: "sealed-evolving-skies-box",
    type: "sealed",
    name: "Evolving Skies Booster Box",
    set: "Evolving Skies",
    number: "Sealed",
    rarity: "Booster box",
    hasPrice: true,
    valueMinor: 45000,
    confidence: "Fair",
    priceSource: "tcgcsv",
    priceObservedAt: "2026-06-01T00:00:00.000Z",
    priceHistory: samplePriceHistory("tcgcsv", "Fair", [
      ["2026-04-01", 42000, "Factory sealed"],
      ["2026-05-01", 43500, "Factory sealed"],
      ["2026-06-01", 45000, "Factory sealed"],
    ]),
    variantOptions: [
      { label: "Factory sealed", valueMinor: 45000, confidence: "Fair", source: "tcgcsv", observedAt: "2026-06-01T00:00:00.000Z" },
    ],
  },
];

export const initialCollection: CollectionItem[] = [
  {
    id: "owned-umbreon",
    catalogueId: "card-umbreon-vmax",
    quantity: 1,
    condition: "Near mint",
    language: "English",
    variant: "Alternate art",
    grade: "Raw",
    purchasePriceMinor: 32000,
    purchaseDate: "2024-11-12",
    location: "Blue Binder",
    notes: "Long-term hold.",
  },
  {
    id: "owned-charizard",
    catalogueId: "card-charizard-151",
    quantity: 1,
    condition: "Near mint",
    language: "English",
    variant: "Reverse Holo",
    grade: "Raw",
    purchasePriceMinor: 9200,
    purchaseDate: "2026-05-01",
    location: "Blue Binder",
    notes: "Bought at card show.",
    overrideValueMinor: 11800,
    valuationNote: "Manual estimate from recent local card show comps.",
  },
  {
    id: "owned-bundle",
    catalogueId: "sealed-151-bundle",
    quantity: 2,
    condition: "Sealed",
    language: "English",
    variant: "Factory sealed",
    grade: "N/A",
    purchasePriceMinor: 4800,
    purchaseDate: "2025-08-18",
    location: "Sealed Box 1",
    notes: "Keep sealed.",
  },
];

export const initialWishlist: WishlistItem[] = [
  {
    id: "want-mew",
    catalogueId: "card-mew-ex",
    priority: "High",
    targetPriceMinor: 3500,
    notes: "Clean copy preferred.",
  },
  {
    id: "want-box",
    catalogueId: "sealed-evolving-skies-box",
    priority: "Grail",
    targetPriceMinor: 45000,
    notes: "Only at the right price.",
  },
];

export const setProgress: SetProgress[] = [
  {
    id: "set-151",
    name: "Scarlet & Violet 151",
    owned: 128,
    total: 207,
  },
  {
    id: "set-crown-zenith",
    name: "Crown Zenith",
    owned: 96,
    total: 159,
  },
  {
    id: "set-evolving-skies",
    name: "Evolving Skies",
    owned: 42,
    total: 237,
  },
];

export const storageLocations: StorageLocation[] = [
  {
    id: "storage-blue-binder",
    name: "Blue Binder",
    type: "Binder",
    itemCount: 2,
    totalQuantity: 2,
    valueMinor: 85800,
  },
  {
    id: "storage-sealed-box-1",
    name: "Sealed Box 1",
    type: "Box",
    itemCount: 1,
    totalQuantity: 2,
    valueMinor: 6400,
  },
  {
    id: "storage-safe",
    name: "Safe",
    type: "Safe",
    notes: "Reserved for graded slabs and higher value sealed items.",
    itemCount: 0,
    totalQuantity: 0,
    valueMinor: 0,
  },
];

export const collectionEvents: CollectionEvent[] = [
  {
    id: "event-pikachu-sold",
    type: "Sold",
    itemId: "owned-pikachu-sold",
    catalogueId: "card-pikachu",
    itemName: "Pikachu",
    quantity: 1,
    amountMinor: 2600,
    basisMinor: 1450,
    currency: "GBP",
    occurredAt: "2026-04-18",
    notes: "Sold duplicate copy.",
  },
  {
    id: "event-charizard-added",
    type: "Added",
    itemId: "owned-charizard",
    catalogueId: "card-charizard-151",
    itemName: "Charizard ex",
    quantity: 1,
    occurredAt: "2026-05-01",
    notes: "Bought at card show.",
  },
  {
    id: "event-bundle-added",
    type: "Added",
    itemId: "owned-bundle",
    catalogueId: "sealed-151-bundle",
    itemName: "151 Booster Bundle",
    quantity: 2,
    occurredAt: "2025-08-18",
    notes: "Keep sealed.",
  },
  {
    id: "event-umbreon-added",
    type: "Added",
    itemId: "owned-umbreon",
    catalogueId: "card-umbreon-vmax",
    itemName: "Umbreon VMAX",
    quantity: 1,
    occurredAt: "2024-11-12",
    notes: "Long-term hold.",
  },
];

export const sampleAppData: AppData = {
  catalogue,
  collection: initialCollection,
  wishlist: initialWishlist,
  sets: setProgress,
  storageLocations,
  events: collectionEvents,
  source: "sample",
  subscription: {
    plan: "free",
    entitlements: {
      "billing.portal": false,
      "exports.insurance_report": false,
      "pricing.alerts": false,
    },
  },
  notificationPreferences: {
    priceAlertsEnabled: true,
    wishlistTargetAlertsEnabled: true,
    weakPriceAlertsEnabled: true,
    digestFrequency: "Daily",
  },
  notice: "Using sample data because no database connection is active.",
};
