import type { CatalogueItem, CollectionItem, SetProgress, WishlistItem } from "./types";

export const catalogue: CatalogueItem[] = [
  {
    id: "card-charizard-151",
    type: "card",
    name: "Charizard ex",
    set: "Scarlet & Violet 151",
    number: "199/165",
    rarity: "Special Illustration Rare",
    image: "https://images.pokemontcg.io/sv3pt5/199_hires.png",
    valueMinor: 11800,
    confidence: "Fair",
  },
  {
    id: "card-umbreon-vmax",
    type: "card",
    name: "Umbreon VMAX",
    set: "Evolving Skies",
    number: "215/203",
    rarity: "Secret Rare",
    image: "https://images.pokemontcg.io/swsh7/215_hires.png",
    valueMinor: 74000,
    confidence: "Strong",
  },
  {
    id: "card-mew-ex",
    type: "card",
    name: "Mew ex",
    set: "Scarlet & Violet 151",
    number: "193/165",
    rarity: "Special Illustration Rare",
    image: "https://images.pokemontcg.io/sv3pt5/193_hires.png",
    valueMinor: 3500,
    confidence: "Fair",
  },
  {
    id: "card-pikachu",
    type: "card",
    name: "Pikachu",
    set: "Crown Zenith",
    number: "160/159",
    rarity: "Secret Rare",
    image: "https://images.pokemontcg.io/swsh12pt5/160_hires.png",
    valueMinor: 1450,
    confidence: "Strong",
  },
  {
    id: "sealed-151-bundle",
    type: "sealed",
    name: "151 Booster Bundle",
    set: "Scarlet & Violet 151",
    number: "Sealed",
    rarity: "Booster bundle",
    valueMinor: 3200,
    confidence: "Weak",
  },
  {
    id: "sealed-evolving-skies-box",
    type: "sealed",
    name: "Evolving Skies Booster Box",
    set: "Evolving Skies",
    number: "Sealed",
    rarity: "Booster box",
    valueMinor: 45000,
    confidence: "Fair",
  },
];

export const initialCollection: CollectionItem[] = [
  {
    id: "owned-umbreon",
    catalogueId: "card-umbreon-vmax",
    quantity: 1,
    condition: "Near mint",
    language: "English",
    variant: "Alternate art",
    grade: "Raw",
    purchasePriceMinor: 32000,
    purchaseDate: "2024-11-12",
    location: "Blue Binder",
    notes: "Long-term hold.",
  },
  {
    id: "owned-charizard",
    catalogueId: "card-charizard-151",
    quantity: 1,
    condition: "Near mint",
    language: "English",
    variant: "Reverse Holo",
    grade: "Raw",
    purchasePriceMinor: 9200,
    purchaseDate: "2026-05-01",
    location: "Blue Binder",
    notes: "Bought at card show.",
    overrideValueMinor: 11800,
  },
  {
    id: "owned-bundle",
    catalogueId: "sealed-151-bundle",
    quantity: 2,
    condition: "Sealed",
    language: "English",
    variant: "Factory sealed",
    grade: "N/A",
    purchasePriceMinor: 4800,
    purchaseDate: "2025-08-18",
    location: "Sealed Box 1",
    notes: "Keep sealed.",
  },
];

export const initialWishlist: WishlistItem[] = [
  {
    id: "want-mew",
    catalogueId: "card-mew-ex",
    priority: "High",
    targetPriceMinor: 3500,
    notes: "Clean copy preferred.",
  },
  {
    id: "want-box",
    catalogueId: "sealed-evolving-skies-box",
    priority: "Grail",
    targetPriceMinor: 45000,
    notes: "Only at the right price.",
  },
];

export const setProgress: SetProgress[] = [
  {
    id: "set-151",
    name: "Scarlet & Violet 151",
    owned: 128,
    total: 207,
  },
  {
    id: "set-crown-zenith",
    name: "Crown Zenith",
    owned: 96,
    total: 159,
  },
  {
    id: "set-evolving-skies",
    name: "Evolving Skies",
    owned: 42,
    total: 237,
  },
];

